/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import javax.swing.UIManager;

/**
 *
 * @author gabriel
 */
public class SelecaoPoltrona extends javax.swing.JFrame {

    /**
     * Creates new form menu4
     */
    public SelecaoPoltrona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel1.setText("   A         B         C         D         E         F         G");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 480, 30));

        jLabel2.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel2.setText("5");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel3.setText("1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel5.setText("2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel6.setText("3");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Alice", 1, 24)); // NOI18N
        jLabel7.setText("4");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Alice", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Poltronas Sala");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 540, 70));

        jButton2.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 60, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 60, -1));

        jButton6.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 60, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 60, -1));

        jButton8.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 60, -1));

        jButton14.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        jButton15.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 60, -1));

        jButton16.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 60, -1));

        jButton17.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 60, -1));

        jButton18.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 60, -1));

        jButton19.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 60, -1));

        jButton20.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 60, -1));

        jButton21.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 60, -1));

        jButton22.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 60, -1));

        jButton23.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, -1));

        jButton24.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 60, -1));

        jButton25.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 60, -1));

        jButton26.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, -1));

        jButton27.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 60, -1));

        jButton28.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 60, -1));

        jButton29.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 60, -1));

        jButton30.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 60, -1));

        jButton31.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 60, -1));

        jButton32.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 60, -1));

        jButton33.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 60, -1));

        jButton34.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 60, -1));

        jButton35.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 60, -1));

        jButton36.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 60, -1));

        jButton37.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 60, -1));

        jButton38.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 60, -1));

        jButton39.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 60, -1));

        jButton40.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 60, -1));

        jButton41.setIcon(new javax.swing.ImageIcon("/home/gabriel/Imagens/poltrona2.png")); // NOI18N
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 60, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 512, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 512, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 510, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 510, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 10, 430));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 10, 430));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 10, 430));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 10, 430));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 10, 430));

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 10, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 540, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
         try 
        {
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
        } 
            catch (Exception e) 
        {
             e.printStackTrace();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoPoltrona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
