/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menus;

/**
 *
 * @author gabriel
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Login_2
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbSair = new javax.swing.JButton();
        jlNomeUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbCancelamento = new javax.swing.JButton();
        jbFechamento = new javax.swing.JButton();
        jbSuperUser = new javax.swing.JButton();
        jbHome = new javax.swing.JButton();
        jbPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel7 = new javax.swing.JPanel();
        jScrollBar2 = new javax.swing.JScrollBar();
        jpPedido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpCancelamento = new javax.swing.JPanel();
        jpFechamento = new javax.swing.JPanel();
        jpSuperUser = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(36, 47, 65));

        jLabel6.setFont(new java.awt.Font("Bebas", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("www.devcodes.com.br");
        jPanel6.add(jLabel6);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 560, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(36, 47, 65));

        jLabel5.setFont(new java.awt.Font("Bebas", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("DevCodes");
        jPanel5.add(jLabel5);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 30));

        jPanel4.setBackground(new java.awt.Color(36, 47, 65));
        jPanel4.setForeground(new java.awt.Color(36, 47, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSair.setBackground(new java.awt.Color(229, 91, 0));
        jbSair.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("Sair");
        jbSair.setBorder(null);
        jbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSairMouseClicked(evt);
            }
        });
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        jPanel4.add(jbSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 80, 20));

        jlNomeUsuario.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jlNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNomeUsuario.setIcon(new javax.swing.ImageIcon("/home/gabriel/user-icon.png")); // NOI18N
        jlNomeUsuario.setText("    Usuario");
        jPanel4.add(jlNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 160, 70));

        jPanel2.setBackground(new java.awt.Color(229, 91, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setForeground(new java.awt.Color(238, 238, 238));
        jPanel2.setToolTipText("");
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 30, 70, 70));

        jbCancelamento.setBackground(new java.awt.Color(229, 91, 0));
        jbCancelamento.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbCancelamento.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelamento.setIcon(new javax.swing.ImageIcon("/home/gabriel/Downloads/cancel.png")); // NOI18N
        jbCancelamento.setText("Cancelamento");
        jbCancelamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 91, 0), 4));
        jbCancelamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbCancelamento.setIconTextGap(30);
        jbCancelamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCancelamentoMouseClicked(evt);
            }
        });
        jbCancelamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelamentoActionPerformed(evt);
            }
        });
        jPanel4.add(jbCancelamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 40));

        jbFechamento.setBackground(new java.awt.Color(229, 91, 0));
        jbFechamento.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbFechamento.setForeground(new java.awt.Color(255, 255, 255));
        jbFechamento.setIcon(new javax.swing.ImageIcon("/home/gabriel/Downloads/dollar-symbol.png")); // NOI18N
        jbFechamento.setText("Fechamento de Caixa");
        jbFechamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 91, 0), 4));
        jbFechamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbFechamento.setIconTextGap(7);
        jbFechamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbFechamentoMouseClicked(evt);
            }
        });
        jbFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFechamentoActionPerformed(evt);
            }
        });
        jPanel4.add(jbFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 40));

        jbSuperUser.setBackground(new java.awt.Color(229, 91, 0));
        jbSuperUser.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbSuperUser.setForeground(new java.awt.Color(255, 255, 255));
        jbSuperUser.setIcon(new javax.swing.ImageIcon("/home/gabriel/Downloads/file.png")); // NOI18N
        jbSuperUser.setText("Super User");
        jbSuperUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 91, 0), 4));
        jbSuperUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbSuperUser.setIconTextGap(45);
        jbSuperUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSuperUserMouseClicked(evt);
            }
        });
        jbSuperUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuperUserActionPerformed(evt);
            }
        });
        jPanel4.add(jbSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 230, 40));

        jbHome.setBackground(new java.awt.Color(229, 91, 0));
        jbHome.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbHome.setForeground(new java.awt.Color(255, 255, 255));
        jbHome.setIcon(new javax.swing.ImageIcon("/home/gabriel/Downloads/house (1).png")); // NOI18N
        jbHome.setText("Home");
        jbHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 91, 0), 4));
        jbHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbHome.setIconTextGap(70);
        jbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbHomeMouseClicked(evt);
            }
        });
        jbHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHomeActionPerformed(evt);
            }
        });
        jPanel4.add(jbHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 40));

        jbPedido.setBackground(new java.awt.Color(229, 91, 0));
        jbPedido.setFont(new java.awt.Font("Alice", 1, 18)); // NOI18N
        jbPedido.setForeground(new java.awt.Color(255, 255, 255));
        jbPedido.setIcon(new javax.swing.ImageIcon("/home/gabriel/Downloads/checked.png")); // NOI18N
        jbPedido.setText("Pedido");
        jbPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 91, 0), 4));
        jbPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPedido.setIconTextGap(65);
        jbPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPedidoMouseClicked(evt);
            }
        });
        jbPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidoActionPerformed(evt);
            }
        });
        jPanel4.add(jbPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 40));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 230, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, -1));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 230, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bebas", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 47, 65));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("filmes em cartaz");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 550, 70));

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollBar1.setBackground(new java.awt.Color(36, 47, 65));
        jScrollBar1.setFont(new java.awt.Font("Bebas", 0, 12)); // NOI18N
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel3.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 490, 20));

        jLayeredPane1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 490, 190));

        jPanel7.setBackground(new java.awt.Color(36, 47, 65));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollBar2.setBackground(new java.awt.Color(36, 47, 65));
        jScrollBar2.setFont(new java.awt.Font("Bebas", 0, 12)); // NOI18N
        jScrollBar2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jPanel7.add(jScrollBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 490, 20));

        jLayeredPane1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jpPedido.setBackground(new java.awt.Color(204, 204, 204));
        jpPedido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Bebas", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("filmes rodando");
        jpPedido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 550, -1));

        jLayeredPane1.add(jpPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        jpCancelamento.setBackground(new java.awt.Color(204, 0, 0));
        jpCancelamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jpCancelamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        jpFechamento.setBackground(new java.awt.Color(0, 153, 153));
        jpFechamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jpFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        jpSuperUser.setBackground(new java.awt.Color(255, 255, 0));
        jpSuperUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(jpSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 540));

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 560, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSairMouseClicked

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbCancelamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelamentoMouseClicked

    private void jbCancelamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelamentoActionPerformed
        jpPedido.setVisible(false);
        jpCancelamento.setVisible(true);
        jpFechamento.setVisible(false);
        jpSuperUser.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jbCancelamentoActionPerformed

    private void jbFechamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbFechamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFechamentoMouseClicked

    private void jbFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFechamentoActionPerformed
        jpPedido.setVisible(false);
        jpCancelamento.setVisible(false);
        jpFechamento.setVisible(true);
        jpSuperUser.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jbFechamentoActionPerformed

    private void jbSuperUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSuperUserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSuperUserMouseClicked

    private void jbSuperUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuperUserActionPerformed
        jpPedido.setVisible(false);
        jpCancelamento.setVisible(false);
        jpFechamento.setVisible(false);
        jpSuperUser.setVisible(true);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jbSuperUserActionPerformed

    private void jbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbHomeMouseClicked

    private void jbHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHomeActionPerformed
        jpPedido.setVisible(false);
        jpCancelamento.setVisible(false);
        jpFechamento.setVisible(false);
        jpSuperUser.setVisible(false);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
    }//GEN-LAST:event_jbHomeActionPerformed

    private void jbPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPedidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPedidoMouseClicked

    private void jbPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidoActionPerformed
        jpPedido.setVisible(true);
        jpCancelamento.setVisible(false);
        jpFechamento.setVisible(false);
        jpSuperUser.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jbPedidoActionPerformed

    public void alterarNomeUsuario(String nome){
        jlNomeUsuario.setText(nome);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jbCancelamento;
    private javax.swing.JButton jbFechamento;
    private javax.swing.JButton jbHome;
    private javax.swing.JButton jbPedido;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSuperUser;
    private javax.swing.JLabel jlNomeUsuario;
    private javax.swing.JPanel jpCancelamento;
    private javax.swing.JPanel jpFechamento;
    private javax.swing.JPanel jpPedido;
    private javax.swing.JPanel jpSuperUser;
    // End of variables declaration//GEN-END:variables
}
